spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173, http://localhost:3000, http://app1.localhost:3000, http://app2.localhost:3000, http://localhost:4200"
            allowedHeaders: "*"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE